// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using LiveLarson.Enums;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine;

namespace DataTables
{
    public class AudioConst : ScriptableObject
{
        [Serializable]
        public class DataClass
        {
            public string LoadingBGM;
            public string OuterSpaceBGM;
        }

    public DataClass Data;
}
}

