// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using LiveLarson.Enums;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine;

namespace DataTables
{
    public class GameConst : ScriptableObject
{
        [Serializable]
        public class DataClass
        {
            public List<string> AgentNames;
            public List<string> AgentNumbers;
            public List<string> AgentGenerations;
            public List<string> AgentLevelNames;
            public string InserterCollision;
            public string SlotCollision;
            public float increaseSliderValuePerCorrectRecycle;
            public string sfxCorrectRecycle;
            public string sfxWrongRecycle;
            public string sfxInstruction;
        }

    public DataClass Data;
}
}

