// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using LiveLarson.Enums;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine;

namespace DataTables
{
    [Serializable]
    public class GadgetInfo
    {
        public int ID;
        [JsonConverter(typeof(StringEnumConverter))]
        public GadgetType GadgetType;
        public string Name;
        public string Description;
        public string PreviewPath;
        public string ModelPath;
        public bool HasFromStart;
    }

}

