// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using LiveLarson.Enums;
using UnityEngine;

namespace DataTables
{
    [Serializable]
    public class Mission
    {
        public int ID;
        public string Title;
    }

}

