// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using LiveLarson.Enums;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine;

namespace DataTables
{
    [Serializable]
    public class Notification
    {
        public int ID;
        public string Value;
    }

}

