// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using LiveLarson.Enums;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine;

namespace DataTables
{
    [Serializable]
    public class Task
    {
        public int ID;
        [JsonConverter(typeof(StringEnumConverter))]
        public TaskType TaskType;
        public List<string> ValueStrs;
        public List<int> ValueInts;
    }

}

