// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using LiveLarson.Enums;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine;

namespace DataTables
{
    [Serializable]
    public class TaskInfo
    {
        public int ID;
        [JsonConverter(typeof(StringEnumConverter))]
        public TaskType TaskType;
        public int RewardID;
        public string EndActions;
        public List<int> ValueInts;
    }

}

